name: CI/CD for Sauter University

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t your-dockerhub-username/sauter-university .
      - name: Login to Docker Hub
        run: docker login -u your-dockerhub-username -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Push the Docker image
        run: docker push your-dockerhub-username/sauter-university
